---
title: "R Notebook"
output: html_notebook
---

# What kinds of run-specific effects do we see even after filtering for high-quality samples?

```{r}
n_var_by_run<-samples_n_var %>% filter(INSTRUMENT_RESULT<26) %>% ggplot(aes(x=run, y=n_var)) + geom_boxplot() + theme_bw() + theme(axis.text.x=element_text(angle=90))+xlab("Run") + ylab("No. minor variants")
```

```{r}
#are run effects related to sequencing depth?
n_var_by_coverage<-samples_n_var %>% filter(INSTRUMENT_RESULT<26) %>% ggplot(aes(x=median_coverage, y=n_var)) + geom_point(alpha=0.5) + geom_smooth() + theme_bw() + xlab("Sample median coverage") + ylab("No. minor variants in sample")
#not on the individual sample level
```

```{r}
#is average minor variant richness in a run related to average depth of coverage in the run?
n_var_depth_averages<-samples_n_var %>% filter(INSTRUMENT_RESULT<26) %>% group_by(run) %>% summarise(median_n_var=median(n_var), median_sample_coverage=median(median_coverage), median_ct=median(INSTRUMENT_RESULT)) %>% ggplot(aes(x=median_sample_coverage, y=median_n_var)) + geom_point() + theme_bw() + xlab("Run-level median of median coverage") + ylab("Median no. minor variants of samples in run") + geom_smooth(method=lm) 
```

```{r}
samples_n_var %>% filter(INSTRUMENT_RESULT<26) %>% filter(run=="Run_90") %>% ggplot(aes(x=median_coverage, y=n_var)) + geom_point() + ggtitle("Run 90 - very high average coverage") + theme_bw() + geom_hline(yintercept=10, linetype="dotted")
```

```{r}
samples_n_var %>% filter(INSTRUMENT_RESULT<26) %>% filter(run=="Run_29") %>% ggplot(aes(x=median_coverage, y=n_var)) + geom_point() + ggtitle("Run 29 - lower average coverage") + theme_bw() + geom_hline(yintercept=10, linetype="dotted")
```


```{r}
#are the run-specific differences in coverage stronger in samples that were included or that weren't included?
mcov_samples %>% mutate(hq_sample=if_else(MCoVNumber %in% minor_sites_lowct$MCoVNumber, "hq","excluded")) %>%  ggplot(aes(x=run, y=median_coverage)) + geom_boxplot() +theme_bw() + theme(axis.text.x=element_text(angle=90)) + facet_grid(hq_sample~.) 
```
```{r}
#SUPP FIG 3
plot_grid(n_var_by_run, plot_grid(n_var_by_coverage, n_var_depth_averages, nrow=2), ncol=2, rel_widths = c(2,1), labels=c("a","b"))
```




