---
title: "R Notebook"
output: html_notebook
---
```{r}
source("./scripts/startup.R")
```

Define functions
```{r}

#setup parallel backend to use many processors
normalize <- function(x, na.rm = TRUE) {
  scaled = (x- min(x)) /(max(x)-min(x))
    return(scaled)
}

scale_scan_factors = function(patient_counts_30, scan_factors_trim) {
  p_sub = patient_counts_30 %>% 
  select(MCoVNumber,lineage,Duration,COLLECTION_DT:last_col(),
         one_of(scan_factors_trim)) %>% unique

  p_sub_scaled = p_sub %>% select(one_of(scan_factors_trim)) %>% 
    mutate_if(is.numeric, normalize) %>% # scale will z scale it, instead of the normalize fx above which is min max
    mutate_if(is.character, as.factor) %>%
    cbind(p_sub %>% select(!one_of(scan_factors_trim)))
  return(p_sub_scaled)
}

run_parallel_binom = function(tmp_counts, scan_factors_trim) {
  # define function that parallel needs
    parallel_binom = function(tmp_counts, scan_factors_trim, idx, model_type = "nbinom2") {
        if (model_type == "nbinom2") dv = "n_var" else dv = "high_counts"
        formula = formula(paste0(dv, "~", scan_factors_trim[idx], "+ CT + (1|run)"))
        flag = T
        model = tryCatch(glmmTMB(formula = formula, 
                         data = tmp_counts, family = model_type), 
                         error = function(e) flag <<- F)
        if (!flag) return(NULL)
        tmp = summary(model)
        test_factor = tmp_counts %>% pull(one_of(scan_factors_trim[idx]))
        model_coef = tmp$coefficients$cond %>% as.data.frame() %>% 
          select(Estimate, `Std. Error`, pval=`Pr(>|z|)`) %>% .[2,] %>% 
          mutate(model_type = model_type,
                 model_target_factor = rownames(.),
                 target_factor = ifelse(is.factor(test_factor), levels(test_factor)[2], NA),
                 ref_factor = ifelse(is.factor(test_factor), levels(test_factor)[1], NA),
                 high_counts = tmp_counts$high_counts_threshold[1],
                 name = scan_factors_trim[idx],
                 LL = Estimate - 1.96*`Std. Error`,
                 UL = Estimate + 1.96*`Std. Error`)
        return(model_coef)
    }
  
  # run the above function in parallel
  cores=detectCores()
  cl <- makeCluster(cores[1]-1) #not to overload your computer
  registerDoParallel(cl)
  finalMatrix <- foreach(idx=1:length(scan_factors_trim), .combine=rbind,
                         .packages=c("glmmTMB", "tidyverse")) %dopar% {
   tempMatrix_nb = parallel_binom(tmp_counts, scan_factors_trim, idx, model_type = "nbinom2")
   tempMatrix_binom = parallel_binom(tmp_counts, scan_factors_trim, idx, model_type = "binomial")

   tempMatrix_out = rbind(tempMatrix_nb, tempMatrix_binom)
   tempMatrix_out #Equivalent to finalMatrix = rbind(finalMatrix, tempMatrix)
  }
  stopCluster(cl)
  return(finalMatrix)
}

scale_and_run_binom = function(patient_counts_30, scan_factors_trim) {
  tmp_counts = scale_scan_factors(patient_counts_30, scan_factors_trim) %>% 
  mutate(high_counts_threshold = quantile(.$n_var, probs = .5)[[1]], 
         high_counts = n_var > high_counts_threshold)
  model_coef = run_parallel_binom(tmp_counts, scan_factors_trim)
  
  # count the occurrences
  n_model = tmp_counts %>% select(any_of(scan_factors_trim)) %>% 
    select_if(~class(.) == 'factor') %>%
      gather(name, value) %>%  # reshape dataset
      count(name, value) %>%     # count combinations
      group_by(name) %>% 
      summarize(factor_count = n[2], factor_prop = factor_count / sum(n))
  
  model_coef_n = model_coef %>% left_join(n_model)
  
  return(model_coef_n)
}

forest_tn = function(df_input, model_count = 2, alt = F) {
  df_input = df_input %>% filter(factor_prop > 0.05 & factor_prop < 0.95)
  order = df_input %>% group_by(name) %>% summarize(mean_estimate = mean(Estimate)) %>% 
  arrange(mean_estimate) %>% pull(name)
  
  df_input$name = factor(df_input$name, levels = order)
  both_pass = df_input %>% group_by(name) %>% 
  summarize(both_pass = (sum(pval < 0.05) > (model_count - 1))) %>% arrange(name, order) %>%
  mutate(both_pass = ifelse(both_pass, "black", "grey")) %>%
  pull(both_pass)

  forest_binom = df_input  %>%
    mutate(name = factor(name, levels = order)) %>%
    ggplot(aes(x = (Estimate), y = name)) +
    geom_vline(xintercept = 0, linetype = "solid") 
  
  if (alt == T) {
    forest_binom =forest_binom + geom_effect(aes(xmin = (LL), xmax = (UL), 
                    color = Source, filled = pval < 0.05)) + 
    theme_forest() + theme(legend.position = "right", 
                           axis.text.x = element_text(angle = 90, 
                                                      vjust = 0.5, hjust=1)) + 
    geom_stripes() +
    scale_x_continuous(sec.axis = sec_axis(~ exp(.), breaks = c(seq(0.4,1.4,0.2), 2))) + #,
    xlab("exp(Coefficient)")
  } else {
    
    forest_binom = forest_binom + geom_effect(aes(xmin = (LL), xmax = (UL), 
                    color = model_type, filled = pval < 0.05)) + 
    theme_forest() + theme(legend.position = "top", 
                           axis.text.x = element_text(angle = 90, 
                                                      vjust = 0.5, hjust=1),
                           axis.text.y = element_text(color = both_pass)) + 
    geom_stripes() +
    scale_x_continuous(sec.axis = sec_axis(~ exp(.), breaks = c(seq(0.4,1.4,0.2), 2))) + 
    xlab("exp(Coefficient)")
  }
  return(forest_binom)
}

```

Run functions for negative binomial and binomial regression
``` {r}
scan_factors_trim = c('Duration','age18under','age55plus','sex','chronic_lung_disease',
                 'chronic_liver_disease', 'chronic_kidney_disease', 'chronic_heart_disease', 
                  'hypertension', 'diabetes', 'cancer', 'obesity', 
                 'plasma', 'mAb', 'admitted_hospital','vaccine_status',
                 'vocAlpha','vocDelta',
                 'surveillance','CT','median_coverage', 'PUI')


patient_counts_30 = read_feather("processing/patient_counts_30.arrow") %>% 
  mutate(PUI = as.factor(PUI))

all_data = scale_and_run_binom(patient_counts_30, scan_factors_trim)
afterJuly = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(collection_date >= "2021-07-01"), 
                                   scan_factors_trim)
beforeJuly = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(collection_date <= "2021-07-01"), 
                                   scan_factors_trim)

afterJuly_IP = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(admitted_hospital == 1 & 
                                            collection_date >= "2021-07-01"), 
                                   scan_factors_trim)
beforeJuly_IP = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(admitted_hospital == 1 & 
                                            collection_date <= "2021-07-01"), 
                                   scan_factors_trim)
afterJuly_OP = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(admitted_hospital == 0 & 
                                            collection_date >= "2021-07-01"), 
                                   scan_factors_trim)
beforeJuly_OP = scale_and_run_binom(patient_counts_30 %>% 
                                   filter(admitted_hospital == 0 & 
                                            collection_date <= "2021-07-01"), 
                                   scan_factors_trim)

dfnames = c("all_data", "afterJuly", "beforeJuly", "afterJuly_IP", 
            "beforeJuly_IP", "afterJuly_OP", "beforeJuly_OP")
all_df_binom_nb = do.call(rbind, lapply(dfnames, function(x) cbind(get(x), Source=x)))
write_feather(all_df_binom_nb, "processing/temp_all_df_binom_nb.arrow")
```


# Plot the forest plots
```{r}
all_df_binom_nb = read_feather("processing/temp_all_df_binom_nb.arrow")
df_input = all_df_binom_nb %>% filter(Source == "all_data") %>% select(-Source)
all_forest = forest_tn(all_df_binom_nb %>% filter(Source == "all_data"))
all_forest

after_July_forest = forest_tn(all_df_binom_nb %>% filter(Source == "afterJuly")) + 
  labs(caption = "07/2021-12/2021")

before_July_forest = forest_tn(all_df_binom_nb %>% filter(Source == "beforeJuly")) + 
  labs(caption = "12/2020-07/2021")

July_forest = ggarrange(before_July_forest, 
          after_July_forest,  ncol = 2, 
          common.legend = T, labels = list("A", "B"))
July_forest

ggsave("ggsave/July_forest.pdf", July_forest, width = 10, height = 4)
```
# 
```{r}
afterJuly_IP_forest = forest_tn(all_df_binom_nb %>% filter(Source == "afterJuly_IP"))
beforeJuly_IP_forest = forest_tn(all_df_binom_nb %>% filter(Source == "beforeJuly_IP"))
afterJuly_OP_forest = forest_tn(all_df_binom_nb %>% filter(Source == "afterJuly_OP"))
beforeJuly_OP_forest = forest_tn(all_df_binom_nb %>% filter(Source == "beforeJuly_OP"))


dissected_July_forest = ggarrange(beforeJuly_IP_forest, afterJuly_IP_forest, 
          beforeJuly_OP_forest, afterJuly_OP_forest, ncol = 2, nrow = 2, 
          common.legend = T, legend = "bottom", labels = "AUTO")

dissected_July_forest_anno = annotate_figure(dissected_July_forest, 
                                             top = "Before or After July 2021", 
                                             left = "Outpatient or Inpatient")
dissected_July_forest_anno

ggsave("ggsave/dissected_July_forest_anno.pdf", 
       dissected_July_forest_anno, 
       height = 6, width = 8)
```




# ALTERNATIVE DATASETS
```{r}
# No count restriction 
patient_counts = read_feather("processing/patient_counts.arrow")
initial_scan_nocount = scale_and_run_binom(patient_counts %>% 
                               filter(n_var > 30), 
                               scan_factors_trim)
#forest_tn(initial_scan_nocount %>% filter(model_type == "nbinom2"), model_count = 1)


# 500x98%
patient_counts_30 = read_feather("processing/patient_counts_30.arrow")
initial_scan_500x98 = scale_and_run_binom(patient_counts_30 %>% filter(fraction_1000x_coverage > .98),
                                          scan_factors_trim)

#forest_tn(initial_scan_500x98 %>% filter(model_type == "binomial"), model_count = 1)


# CT < 18
initial_scan_ct18 = scale_and_run_binom(patient_counts_30 %>% filter(INSTRUMENT_RESULT < 18) %>%
                                          mutate(PUI = as.factor(PUI)),
                                        scan_factors_trim)
#forest_tn(initial_scan_ct18 %>% filter(model_type == "binomial"), model_count = 1)

# No co-morbidity
initial_scan_no_comorbid = scale_and_run_binom(patient_counts_30 %>% 
      filter(chronic_heart_disease == 0, diabetes == 0, chronic_lung_disease == 0,
             chronic_liver_disease == 0, chronic_kidney_disease == 0, cancer == 0,
             hypertension == 0, hiv == 0, transplant_patient == 0, surveillance == 0), scan_factors_trim)

#forest_tn(initial_scan_no_comorbid %>% filter(model_type == "binomial"), model_count = 1)


dfnames = c("df_input", "initial_scan_nocount", "initial_scan_500x98", 
            "initial_scan_ct18", "initial_scan_no_comorbid")
df_input = all_df_binom_nb %>% filter(Source == "all_data") %>% select(-Source)

alt_binom = do.call(rbind, lapply(dfnames, function(x) cbind(get(x), Source=x)))

alt_to_plot = alt_binom %>% filter(model_type == "binomial")
forest_binomial = forest_tn(alt_to_plot, alt = T)
alt_to_plot_nbinom = alt_binom %>% filter(model_type == "nbinom2")
forest_nbinom = forest_tn(alt_to_plot_nbinom, alt = T)
forest_nbinom


alt_forests = ggarrange(forest_binomial, forest_nbinom, ncol = 2, common.legend = T,
                        legend = "bottom", labels = "AUTO") %>% 
  annotate_figure(top = "binomial or nbinom2 model")

ggsave("ggsave/alt_forests.pdf", alt_forests, width = 9, height = 6.5)
```