---
title: "R Notebook"
output: html_notebook
---

```{r, fig.width = 2, fig.height = 2.5}
source("./scripts/startup.R")
source("./scripts/load_data.R")
library(magrittr)

  
gene_counts = patient_var_30 %>% #left_join(immunocompromised) %>%
  #filter(admitted_hospital == 1) %>%
  group_by(MCoVNumber, gene) %>% 
  summarize(g_var = n()) %>% group_by(MCoVNumber) %>% 
  mutate(n_var = sum(g_var)) %>% 
  select(!n_var) %>% filter(gene!="") %>%
  pivot_wider(names_from = "gene", values_from = g_var, values_fill = 0)

genes = patient_var %>% pull(gene) %>% unique

patient_counts_uni_tmp = fread("processing/patient_counts_for_modeling.txt", data.table = F)
exclude = c("lineage", "MCoVNumber" , "COLLECTION_DT" , "run",
            "filename", "fraction_100x_coverage", "fraction_200x_coverage",
            "fraction_500x_coverage", "n", "mcov_id",
            "run_group", "RECEIVE_DT","VERIFIED_DT", "ordinal_counts")

  
include = colnames(patient_counts_uni_tmp) %>% as.data.frame %>% 
  filter(!. %in% exclude) %>% filter(str_detect(.,'__')) %>% pull(.)
meta = patient_counts_uni_tmp %>% select(c("MCoVNumber", include,"n_var")) %>%
  select(!contains("0")) %>%
  select(!contains("FALSE")) %>%
  select(!contains("high_counts")) %>% #filter(n_var <= 30) %>%
  select(!contains("disease"))

gene_counts_meta = gene_counts %>% left_join(meta)
gene_counts_meta_tmp = gene_counts_meta
y = gene_counts_meta_tmp %>% ungroup %>% select(one_of(genes)) #%>% as.matrix


enrichment = function(y, genes) {
  genes = genes[genes != ""]
  gene_lengths = fread("ntpos_gene_update.csv") %>% 
    mutate(total = max(ntpos)-min(ntpos)+1) %>% 
    group_by(gene_id) %>%
    summarize(start = min(ntpos), end = max(ntpos)) %>% 
    mutate(length = end-start+1, total = max(end), prop = length/total) %>%
    filter(gene_id != "")
  probs = gene_lengths %>% arrange(start) %>% select(gene_id, prop)
  
  index = 0; out = 0; for (gene in genes) {
    index = index + 1
    test_tmp = tryCatch(binom.test(sum(y[gene]), 
                          sum(colSums(y[genes])), probs %>% 
                 filter(gene_id == gene) %>% pull(prop)),
        error=function(e) index<<-0)
      if (index == 0) next
    test = tidy(test_tmp) %>% mutate(gene = gene)
    if (index == 1) {
      out = test
    } else {
      out = rbind(out, test)
    }
  }
  out = out %>% left_join(probs %>% mutate(gene = gene_id))
  
  
  # plot the bars total, admitted, not admitted; vaccine, no vaccine; mab vs no mab.
  out = out %>% mutate(fc = out$estimate / out$prop) %>% arrange(fc)
  out$gene = factor(out$gene, out$gene)
  out$enriched = (out$estimate > out$prop | out$estimate < out$prop)
  out[out$p.value > 0.0001,] %<>% mutate(enriched = FALSE)
  return(out)
}
out = enrichment(y, genes)

out %>% ggplot(aes(y = prop, x = gene, fill = enriched)) + 
  #geom_bar(stat = "identity") + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), ymax = log2(conf.high/prop))) +
  theme_pubr() + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")
# color based on enriched or negative
```

```{r}
# conduct the enrichment plot where you compare observed vs. expected 
# but it's based on a matrix of unique counts at positions instead

unique_gene_counts = patient_var_30 %>% unite(col = "spectra_mutation", 
                                            major, ntpos, minor, remove = FALSE) %>% 
  select(gene, major, minor, spectra_mutation) %>% unique() %>% 
  group_by(gene) %>% 
  summarize(g_var = n()) %>% filter(gene != "") %>%
  pivot_wider(names_from = "gene", values_from = g_var, values_fill = 0)

unique_out = enrichment(unique_gene_counts, genes) %>% mutate(mutation = "unique")
unique_all = rbind(out %>% mutate(mutation = "all"), unique_out)

unique_all_enrichment_plot = unique_all %>% ggplot(aes(y = prop, x = gene, color = mutation)) + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), 
                    ymax = log2(conf.high/prop)), 
                position=position_dodge(width=0.3)) +
  theme_minimal() + theme(legend.position = "top") + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")

unique_all_enrichment_plot

#ggsave("ggsave/unique_all_enrichment_plot.pdf", unique_all_enrichment_plot, height = 4, width = 3.5)

```


```{r}
gene_enrichment_for_plot = function(filtered_patient_var, 
                                    unique = FALSE, label) {
  unique_gene_counts_admitted_tmp = filtered_patient_var %>% 
  unite(col = "spectra_mutation", major, ntpos, minor, remove = FALSE) %>% 
  select(gene, major, minor, spectra_mutation)
  
  if (unique == TRUE) {
    unique_gene_counts_admitted_tmp = unique_gene_counts_admitted_tmp %>% unique()
  }
  
  unique_gene_counts_admitted = unique_gene_counts_admitted_tmp %>% group_by(gene) %>% 
  summarize(g_var = n()) %>% filter(gene != "") %>%
  pivot_wider(names_from = "gene", values_from = g_var, values_fill = 0)
  
  unique_out_admitted = enrichment(unique_gene_counts_admitted, genes) %>% 
    mutate(mutation = label)
  
  return(unique_out_admitted)
}

# ALL COUNTS
out_admitted = gene_enrichment_for_plot(patient_var_30 %>% 
                                                 filter(admitted_hospital == 1), 
                                               unique = FALSE, label = "admitted")
out_outpatient = gene_enrichment_for_plot(patient_var_30 %>% 
                                                   filter(admitted_hospital == 0),
                                                 unique = FALSE, label = "outpatient")
all = rbind(out_admitted, out_outpatient)

all_enrichment_plot = all %>% ggplot(aes(y = prop, x = gene, color = mutation)) + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), 
                    ymax = log2(conf.high/prop)), 
                position=position_dodge(width=0.3)) + scale_y_continuous(limits=c(-2, 2.5)) +
  theme_minimal() + ggtitle("All counts") + theme(legend.position = "top") + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")

# UNIQUE COUNTS
unique_out_admitted = gene_enrichment_for_plot(patient_var_30 %>% 
                                                 filter(admitted_hospital == 1), 
                                               unique = TRUE, label = "admitted")
unique_out_outpatient = gene_enrichment_for_plot(patient_var_30 %>% 
                                                   filter(admitted_hospital == 0),
                                                 unique = TRUE, label = "outpatient")
unique_all = rbind(unique_out_admitted, unique_out_outpatient)

unique_all_enrichment_plot = unique_all %>% mutate(gene = fct_relevel(gene, levels(all$gene))) %>%
  ggplot(aes(y = prop, x = gene, color = mutation)) + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), 
                    ymax = log2(conf.high/prop)), 
                position=position_dodge(width=0.3)) + scale_y_continuous(limits=c(-1, 1.7)) +
  theme_minimal() + ggtitle("Unique counts") + theme(legend.position = "top") + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")

combined_all_unique_enrichment = ggarrange(all_enrichment_plot, unique_all_enrichment_plot, common.legend = T)
combined_all_unique_enrichment

ggsave("ggsave/differential_genes_admitted_hospital.pdf", combined_all_unique_enrichment, height = 4.5, width = 7)
```

# Do the same thing above but for the vaccinated



```{r}
# ALL COUNTS
out_admitted = gene_enrichment_for_plot(patient_var_30  %>% 
                                          filter(collection_date>="2021-07-01") %>%
                                                 filter(vaccine_status == 1), 
                                               unique = FALSE, label = "vaccinated")
out_outpatient = gene_enrichment_for_plot(patient_var_30 %>% filter(collection_date>="2021-07-01") %>%
                                                   filter(vaccine_status == 0),
                                                 unique = FALSE, label = "unvacinated")
all = rbind(out_admitted, out_outpatient)

all_enrichment_plot = all %>% ggplot(aes(y = prop, x = gene, color = mutation)) + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), 
                    ymax = log2(conf.high/prop)), 
                position=position_dodge(width=0.3)) + #scale_y_continuous(limits=c(-2, 2.5)) +
  theme_minimal() + ggtitle(paste0("After July 2021: All counts")) + theme(legend.position = "top") + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")

# UNIQUE COUNTS
unique_out_admitted = gene_enrichment_for_plot(patient_var_30 %>% 
                                                 filter(collection_date>="2021-07-01") %>%
                                                 filter(vaccine_status == 1), 
                                               unique = TRUE, label = "vaccinated")
unique_out_outpatient = gene_enrichment_for_plot(patient_var_30 %>% 
                                                   filter(collection_date>="2021-07-01") %>%
                                                   filter(vaccine_status == 0),
                                                 unique = TRUE, label = "unvacinated")
unique_all = rbind(unique_out_admitted, unique_out_outpatient)

unique_all_enrichment_plot = unique_all %>% mutate(gene = fct_relevel(gene, levels(all$gene))) %>%
  ggplot(aes(y = prop, x = gene, color = mutation)) + 
  geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), 
                    ymax = log2(conf.high/prop)), 
                position=position_dodge(width=0.3)) + #scale_y_continuous(limits=c(-1, 1.7)) +
  theme_minimal() + ggtitle("Unique counts") + theme(legend.position = "top") + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
  ylab("log2FC (observed / expected_counts)")

combined_all_unique_enrichment = ggarrange(all_enrichment_plot, unique_all_enrichment_plot, common.legend = T)
combined_all_unique_enrichment

ggsave("ggsave/differential_genes_vaccine.pdf", combined_all_unique_enrichment, 
       height = 4.5, width = 7)
```


```{r}
# y_with_patient = gene_counts_meta_tmp %>% select(one_of(genes), vaccine_status___1, admitted_hospital___1, mAb___1)
# enrichment(y_with_patient %>% 
#       filter(admitted_hospital___1 == "YES"), genes)
# 
# out_admitted_hospital = (enrichment(y_with_patient %>% 
#       filter(admitted_hospital___1 == "YES"), genes) %>%
#   mutate(condition = "Inpatient")) %>% rbind(
#   (enrichment(y_with_patient %>% 
#       filter(admitted_hospital___1 == "NO"), genes) %>%
#   mutate(condition = "Outpatient"))) %>%
#   ggplot(aes(y = prop, x = gene, color = factor(condition))) + 
#   geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), ymax = log2(conf.high/prop)), position=position_dodge(width=0.3)) +
#   theme_pubr() + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
#   ylab("log2FC (observed / expected_counts)")
# 
# out_vaccine = (enrichment(y_with_patient %>% 
#       filter(vaccine_status___1 == "YES"), genes) %>%
#   mutate(condition = "Vaccinated")) %>% rbind(
#   (enrichment(y_with_patient %>% 
#       filter(vaccine_status___1 == "NO"), genes) %>%
#   mutate(condition = "Unvaccinated"))) %>%
#   ggplot(aes(y = prop, x = gene, color = factor(condition))) + 
#   geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), ymax = log2(conf.high/prop)), position=position_dodge(width=0.3)) +
#   theme_pubr() + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
#   ylab("log2FC (observed / expected_counts)")
# 
# out_vaccine
# 
# out_mAb = (enrichment(y_with_patient %>% 
#       filter(mAb___1 == "YES"), genes) %>%
#   mutate(condition = "Inpatient")) %>% rbind(
#   (enrichment(y_with_patient %>% 
#       filter(mAb___1 == "NO"), genes) %>%
#   mutate(condition = "Outpatient"))) %>%
#   ggplot(aes(y = prop, x = gene, color = factor(condition))) + 
#   geom_errorbar(aes(x = gene, ymin = log2(conf.low/prop), ymax = log2(conf.high/prop)), position=position_dodge(width=0.3)) +
#   theme_pubr() + coord_flip() + geom_hline(yintercept = 0, linetype = "dashed") +
#   ylab("log2FC (observed / expected_counts)")
# 
# out_admitted_hospital_no = enrichment(y_with_patient %>% filter(admitted_hospital___1 == "NO"), genes)
# out_admitted_hospital_no = enrichment(y_with_patient %>% filter(admitted_hospital___1 == "NO"), genes)
# 
# 
# ggsave("ggsave/differential_genes_admitted_hospital.pdf", out_admitted_hospital, height = 5, width = 4.5)

```


